Repository Jungle08-Week09to11-Team09/pintos_lab_docker, pull requests merged in 2025-05, with the labels that each got.

#13 시스템 콜 write/exit 구현
  .gitignore
  pintos-kaist/lib/kernel/console.c
  pintos-kaist/threads/thread.c
  pintos-kaist/userprog/syscall.c
Labels: 김별

#21 exec() 구현 + 64 failed
  pintos-kaist/userprog/build/os.dsk
  pintos-kaist/userprog/syscall.c
Labels: 김별

#23 open() 파일 추가
  pintos-kaist/include/threads/thread.h
  pintos-kaist/include/userprog/syscall.h
  pintos-kaist/threads/thread.c
Labels: 김별

#26 시스템콜 초안 구현
  pintos-kaist/include/threads/thread.h
  pintos-kaist/threads/thread.c
  pintos-kaist/userprog/filesys.dsk
  pintos-kaist/userprog/syscall.c
Labels: 김별

#27 fork 완
  pintos-kaist/threads/thread.c
  pintos-kaist/userprog/build/os.dsk
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
Labels: 김별, 오주영, 백지원

#29 구조체 수정 + #include 안 넣은 거 추가
  .vscode/settings.json
  pintos-kaist/include/threads/thread.h
  pintos-kaist/threads/thread.c
  pintos-kaist/userprog/build/os.dsk
  pintos-kaist/userprog/process.c
  pintos-kaist/userprog/syscall.c
Labels: 백지원
